apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac-bridge.yaml
  - pv.yaml
  - pvc.yaml
  - gpu-timeslicing.yaml
  - bridge.yaml
  - model-preload-job.yaml
  - worker-deployment.yaml
