apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: whisper
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
